name: practicalgitops.prod.infra

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
  pull_request:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "infra" # ✅ Fixed working directory
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # ✅ Updated version

      - name: Uncomment Terraform Cloud Backend Configuration file
        id: uncomment
        run: sed -i '/^#terraform {/,/^#}/s/^#\s*//' backend.tf # ✅ Fixed sed command

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=prod.hcl
